/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.devtime.telas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author rony.sobral@VALEMOBI.CORP
 */
public class TelaComponente extends javax.swing.JFrame {

    /**
     * Creates new form TelaComponente
     */
    public TelaComponente() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        toggleCpu = new javax.swing.JToggleButton();
        toggleRam = new javax.swing.JToggleButton();
        toggleAmarzenamento = new javax.swing.JToggleButton();
        toggleSoftware = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(138, 17, 190));

        jLabel1.setBackground(new java.awt.Color(254, 254, 254));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Componentes sendo captados");

        jPanel2.setBackground(new java.awt.Color(54, 54, 54));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Descrição:");

        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("CPU");

        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("RAM");

        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Armazenamento");

        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Softwares");

        toggleCpu.setBackground(new java.awt.Color(197, 197, 197));
        toggleCpu.setForeground(new java.awt.Color(1, 1, 1));
        toggleCpu.setText("Ativo");
        toggleCpu.setFocusPainted(false);
        toggleCpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleCpuActionPerformed(evt);
            }
        });

        toggleRam.setBackground(new java.awt.Color(197, 197, 197));
        toggleRam.setForeground(new java.awt.Color(1, 1, 1));
        toggleRam.setText("Ativo");
        toggleRam.setFocusPainted(false);
        toggleRam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleRamActionPerformed(evt);
            }
        });

        toggleAmarzenamento.setBackground(new java.awt.Color(197, 197, 197));
        toggleAmarzenamento.setForeground(new java.awt.Color(1, 1, 1));
        toggleAmarzenamento.setText("Ativo");
        toggleAmarzenamento.setFocusPainted(false);
        toggleAmarzenamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleAmarzenamentoActionPerformed(evt);
            }
        });

        toggleSoftware.setBackground(new java.awt.Color(197, 197, 197));
        toggleSoftware.setForeground(new java.awt.Color(1, 1, 1));
        toggleSoftware.setText("Ativo");
        toggleSoftware.setFocusPainted(false);
        toggleSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleSoftwareActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Status");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(toggleAmarzenamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toggleCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toggleRam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toggleSoftware, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(56, 56, 56))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggleCpu)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggleRam)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggleAmarzenamento)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggleSoftware)
                    .addComponent(jLabel5))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toggleSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleSoftwareActionPerformed
        // TODO add your handling code here:

        if (toggleSoftware.isSelected()) {

            String senha = JOptionPane.showInputDialog("Senha:");
            

            if (senha.endsWith("teste123")) {
                toggleSoftware.setText("Desligado");

            } else {
                JFrame jf = new JFrame();

                JOptionPane.showMessageDialog(jf,
                        "Senha Incorreta!!",
                        "Erro", JOptionPane.WARNING_MESSAGE);
            
                toggleSoftware.setSelected(false);
            }

        } else {

            toggleSoftware.setText("Ativo");

        }
    }//GEN-LAST:event_toggleSoftwareActionPerformed

    private void toggleCpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleCpuActionPerformed
        // TODO add your handling code here:

        if (toggleCpu.isSelected()) {

            String senha = JOptionPane.showInputDialog("Senha:");

            if (senha.endsWith("teste123")) {
                toggleCpu.setText("Desligado");

            } else {
                JFrame jf = new JFrame();

                JOptionPane.showMessageDialog(jf,
                        "Senha Incorreta!!",
                        "Erro", JOptionPane.WARNING_MESSAGE);
                
                toggleCpu.setSelected(false);
            }

        } else {

            toggleCpu.setText("Ativo");

        }
    }//GEN-LAST:event_toggleCpuActionPerformed

    private void toggleRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleRamActionPerformed
        // TODO add your handling code here:
        if (toggleRam.isSelected()) {

            String senha = JOptionPane.showInputDialog("Senha:");

            if (senha.endsWith("teste123")) {
                toggleRam.setText("Desligado");

            } else {
                JFrame jf = new JFrame();

                JOptionPane.showMessageDialog(jf,
                        "Senha Incorreta!!",
                        "Erro", JOptionPane.WARNING_MESSAGE);
                
                toggleRam.setSelected(false);
            }

        } else {

            toggleRam.setText("Ativo");

        }
    }//GEN-LAST:event_toggleRamActionPerformed

    private void toggleAmarzenamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleAmarzenamentoActionPerformed
        // TODO add your handling code here:
        if (toggleAmarzenamento.isSelected()) {

           String senha = JOptionPane.showInputDialog("Senha:");

            if (senha.endsWith("teste123")) {
                toggleAmarzenamento.setText("Desligado");

            } else {
                JFrame jf = new JFrame();

                JOptionPane.showMessageDialog(jf,
                        "Senha Incorreta!!",
                        "Erro", JOptionPane.WARNING_MESSAGE);
                
                toggleAmarzenamento.setSelected(false);
            }

        } else {

            toggleAmarzenamento.setText("Ativo");

        }
    }//GEN-LAST:event_toggleAmarzenamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaComponente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton toggleAmarzenamento;
    private javax.swing.JToggleButton toggleCpu;
    private javax.swing.JToggleButton toggleRam;
    private javax.swing.JToggleButton toggleSoftware;
    // End of variables declaration//GEN-END:variables
}
